### ISSUE TITLE
作者是一个自大的疯子吗？不是很懂哦。

### ISSUE THREAD

**Issue by Mahiro2211** [StevenJokess/d2rl#1]
况且这个简历，你发到牛客上估计会被一堆人锐评，没有写技术栈，写的都是些不相关的东西。。。毫无意义，为什么还会觉得自己怀才不遇呢？

**Comment by StevenJokess** [comment]
随缘要个饭而已，施主随便judge，你这么聪明一定很自由很有钱吧，V我50给废物一条活路吧

![image](https://github.com/StevenJokess/d2rl/assets/71307974/9f7b1174-f984-45b3-9324-e333e4ee53b7)
